name: Deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - run: pm2 stop www
      - run: rm -rfv ~/gostev.site/
      - run: cp -r ~/actions-runner/_work/gostev.site/gostev.site/ ~/.
      - run: cd ~/gostev.site/
      - run: npm i
      - run: pm2 start www
